### ISSUE TITLE
credentials.json can't be located?

### ISSUE THREAD

**Issue by Zara82** [Taknok/NadekoBot#11]
Followed the instructions, but trying to run ./NadekoBot on the pi returns this error:

//
09:54:09 C:\Users\PC\Documents\Nadeko\NadekoBot\src\NadekoBot\Services\Impl\BotCredentials | credentials.json is missing. Attempting to load creds from environment variables prefixed with 'NadekoBot_'. Example is in /home/pi/credentials_example.json

Unhandled Exception: Microsoft.Data.Sqlite.SqliteException: SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteRelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at NadekoBot.Services.DbService.GetDbContext() in C:\Users\PC\Documents\Nadeko\NadekoBot\src\NadekoBot\Services\DbService.cs:line 31
   at NadekoBot.NadekoBot..ctor(Int32 shardId, Int32 parentProcessId, Nullable`1 port) in C:\Users\PC\Documents\Nadeko\NadekoBot\src\NadekoBot\NadekoBot.cs:line 86
   at NadekoBot.Program.Main(String[] args) in C:\Users\PC\Documents\Nadeko\NadekoBot\src\NadekoBot\Program.cs:line 15
Aborted
//

Don't know what to do about it, the credentials.json is clearly there and set up corectly, I checked it multiple times. I'm a noob when it comes to programming, so I have no idea how to interpret the rest of the error mesage.

**Comment by Taknok** [comment]
Did you check that `credentials.json` is in the `publish` folder on the rasp ? Be careful that there isn't any space in the name, nor the example.json

**Comment by Zara82** [comment]
Just checked again to be sure, the file is there, properly named and set up on both the raspberry and my PC

**Comment by Taknok** [comment]
It doesn't matter on the PC after the transfer. Could you send a screen shot of your folder organization on rasp, and one of the `credential.json` ?

**Comment by Zara82** [comment]
can't upload a screenshot for some reason, but the folder path on the pi is:
/home/pi/public/publish
in the publish folder there is the json file, which looks like this:

{
  "ClientId": 291496147656632269,
  "BotId": null,
  "Token": "abcdefghijklmnopqrstuvwxyz",
  "OwnerIds": [
    1234567890
  ],
  "LoLApiKey": "",
  "GoogleApiKey": "",
  "MashapeKey": "",
  "OsuApiKey": "",
  "PatreonAccessToken": "",
  "Db": null,
  "TotalShards": 1
}

**Comment by PancakeWaffles5** [comment]
Why would you put your token there? Now people can use your bot without your consent, and raid your server

**Comment by Taknok** [comment]
@PancakeWaffles5 has a point, I suggest you too delete it :/
I don't know what trigger the issue, the file is properly named ? no space added or `s`,`.` etc missing ?
